[package]
name = "openvm-floats-transpiler"
description = "OpenVM transpiler extension for floating point arithmetic"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
openvm-stark-backend = { workspace = true }
openvm-instructions = { workspace = true }
openvm-transpiler = { workspace = true }
openvm-instructions-derive = { workspace = true }
openvm-rv32im-transpiler = { workspace = true }
rrs-lib = { workspace = true }
strum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
