[package]
name = "openvm-rv32f-transpiler"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm-instructions = { path = "../toolchain/instructions" }
openvm-rv32im-transpiler = { path = "../../extensions/rv32im/transpiler" }
openvm-stark-backend = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.2.1-rc.3", default-features = false }
openvm-transpiler = { path = "../toolchain/transpiler" }
rrs-lib = "0.1"

[dev-dependencies]
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.2.1-rc.3", default-features = false }
