[package]
name = "openvm-rv32f-integration-tests"
description = "Integration tests for the OpenVM rv32f transpiler"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm-instructions = { path = "../../toolchain/instructions" }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.2.1-rc.3", default-features = false }
openvm-transpiler = { path = "../../toolchain/transpiler" }
openvm-rv32im-transpiler = { path = "../../../extensions/rv32im/transpiler" }
openvm-rv32f-transpiler = { path = ".." }
eyre = "0.6"
test-case = "3.1"

[features]
default = []
