"""Shared test utilities for executable-spec tests."""
import json
from pathlib import Path

import pytest

TEST_DATA_DIR = Path(__file__).resolve().parent / "test-data"

# E2E programs that always have vectors (generated by default).
E2E_REQUIRED_PROGRAMS = ["fibonacci_stark", "rv32im_fibonacci"]

# E2E programs that require heavy vector generation (e.g. revm_transfer).
# Only included in test parameterization when their vectors exist on disk.
E2E_OPTIONAL_PROGRAMS = ["revm_transfer"]


def load_test_vectors(category: str, name: str) -> dict:
    """Load JSON test vectors from test-data/<category>/<name>.json.

    Args:
        category: Subdirectory under test-data (e.g., "primitives", "fri", "e2e").
        name: Vector file name without extension.

    Returns:
        Parsed JSON dict.

    Raises:
        FileNotFoundError: If the vector file does not exist.
    """
    path = TEST_DATA_DIR / category / f"{name}.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Test vector not found: {path}\n"
            f"Run generate-test-vectors.sh to create test vectors."
        )
    with open(path) as f:
        return json.load(f)


def e2e_program_params():
    """Build pytest params for E2E programs.

    Required programs are always included. Optional programs are only included
    when their vector files exist on disk (generated via heavy vector generation).
    """
    params = [pytest.param(name) for name in E2E_REQUIRED_PROGRAMS]
    for name in E2E_OPTIONAL_PROGRAMS:
        json_path = TEST_DATA_DIR / "e2e" / f"{name}.json"
        if json_path.exists():
            params.append(pytest.param(name))
    return params
