"""Tests for BabyBear field arithmetic.

These tests load golden vectors generated by Plonky3's BabyBear implementation
and verify that the Python field implementation produces identical results.

Vectors are in tests/test-data/primitives/babybear_field.json.
"""
import pytest
from helpers import load_test_vectors


class TestBabyBearField:
    """BabyBear prime field (p = 2^31 - 2^27 + 1) arithmetic."""

    @pytest.fixture
    def vectors(self):
        return load_test_vectors("primitives", "babybear_field")

    def test_addition(self, vectors):
        """Field addition: (a + b) mod p."""
        for case in vectors["addition"]:
            a, b, expected = case["a"], case["b"], case["expected"]
            assert False, f"Not implemented: {a} + {b} should equal {expected}"

    def test_multiplication(self, vectors):
        """Field multiplication: (a * b) mod p."""
        for case in vectors["multiplication"]:
            a, b, expected = case["a"], case["b"], case["expected"]
            assert False, f"Not implemented: {a} * {b} should equal {expected}"

    def test_inverse(self, vectors):
        """Multiplicative inverse: a^(-1) mod p."""
        for case in vectors["inverse"]:
            a, expected = case["a"], case["expected"]
            assert False, f"Not implemented: inverse({a}) should equal {expected}"

    def test_subtraction(self, vectors):
        """Field subtraction: (a - b) mod p."""
        for case in vectors["subtraction"]:
            a, b, expected = case["a"], case["b"], case["expected"]
            assert False, f"Not implemented: {a} - {b} should equal {expected}"

    def test_negation(self, vectors):
        """Additive inverse: -a mod p."""
        for case in vectors["negation"]:
            a, expected = case["a"], case["expected"]
            assert False, f"Not implemented: negation({a}) should equal {expected}"


class TestBabyBearExtensionField:
    """Quartic extension field BabyBear4 (degree-4 over BabyBear)."""

    @pytest.fixture
    def vectors(self):
        return load_test_vectors("primitives", "babybear_ext_field")

    def test_ext_addition(self, vectors):
        """Extension field addition."""
        for case in vectors["addition"]:
            assert False, f"Not implemented: ext field addition"

    def test_ext_multiplication(self, vectors):
        """Extension field multiplication."""
        for case in vectors["multiplication"]:
            assert False, f"Not implemented: ext field multiplication"

    def test_ext_inverse(self, vectors):
        """Extension field inverse."""
        for case in vectors["inverse"]:
            assert False, f"Not implemented: ext field inverse"
