"""End-to-end STARK verifier tests.

These tests load proofs generated by the Rust prover and verify them
with the Python verifier implementation. This is the north star test:
if the Python verifier accepts Rust-generated proofs, the spec is correct.

Vectors are in tests/test-data/e2e/.

- ``fibonacci_stark`` is always available (fast, single-AIR).
- ``rv32im_fibonacci`` is included when its vectors exist (heavy generation).
- ``revm_transfer`` is included when its vectors exist (heavy generation).
"""
import json

import pytest
from helpers import load_test_vectors, e2e_program_params

from protocol.proof import (
    parse_proof_json,
    parse_vk_json,
    parse_fri_params,
)
from protocol.stark import (
    VerificationError,
    verify_stark,
)


def _load_e2e(vectors):
    """Parse proof, VK, and FRI params from e2e test vectors.

    Returns (proof, vk, fri_params).
    """
    assert "verifying_key" in vectors and "vk_bytes_hex" in vectors["verifying_key"], (
        "VK data not available — regenerate test vectors"
    )

    proof_bytes = bytes.fromhex(vectors["proof_bytes_hex"])
    proof_json = json.loads(proof_bytes)
    proof = parse_proof_json(proof_json)

    vk_bytes = bytes.fromhex(vectors["verifying_key"]["vk_bytes_hex"])
    vk_json = json.loads(vk_bytes)
    vk = parse_vk_json(vk_json)

    fri_params = parse_fri_params(vectors["fri_params"])
    return proof, vk, fri_params


class TestStarkVerifierE2E:
    """Python verifier accepts proofs generated by OpenVM Rust prover."""

    @pytest.fixture(params=e2e_program_params())
    def program_name(self, request):
        return request.param

    @pytest.fixture
    def vectors(self, program_name):
        return load_test_vectors("e2e", program_name)

    def test_verify_valid_proof(self, program_name, vectors):
        """Verifier accepts a valid proof from the Rust prover."""
        proof, vk, fri_params = _load_e2e(vectors)
        verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_quotient_commitment(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted quotient commitment."""
        proof, vk, fri_params = _load_e2e(vectors)
        proof.commitments.quotient[0] ^= 1

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_main_commitment(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted main trace commitment."""
        proof, vk, fri_params = _load_e2e(vectors)
        proof.commitments.main_trace[0][0] ^= 1

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_public_value(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted public value."""
        proof, vk, fri_params = _load_e2e(vectors)

        # Find the first AIR that has public values
        found = False
        for ap in proof.per_air:
            if ap.public_values:
                ap.public_values[0] ^= 1
                found = True
                break
        assert found, "No AIR with public values — test vector is incomplete"

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_wrong_vk(self, program_name, vectors):
        """Verifier rejects a proof verified against a modified VK."""
        proof, vk, fri_params = _load_e2e(vectors)
        vk.pre_hash[0] ^= 1

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)
