"""End-to-end STARK verifier tests.

These tests load proofs generated by the Rust prover and verify them
with the Python verifier implementation. This is the north star test:
if the Python verifier accepts Rust-generated proofs, the spec is correct.

Vectors are in tests/test-data/e2e/.
"""
import pytest
from pathlib import Path
from helpers import load_test_vectors, TEST_DATA_DIR


class TestStarkVerifierE2E:
    """Python verifier accepts proofs generated by OpenVM Rust prover."""

    @pytest.fixture(params=["fibonacci"])
    def program_name(self, request):
        return request.param

    @pytest.fixture
    def vectors(self, program_name):
        return load_test_vectors("e2e", program_name)

    @pytest.fixture
    def proof_binary(self, program_name):
        proof_path = TEST_DATA_DIR / "e2e" / f"{program_name}.proof.bin"
        if not proof_path.exists():
            raise FileNotFoundError(
                f"Binary proof not found: {proof_path}\n"
                f"Run generate-test-vectors.sh to create proof artifacts."
            )
        return proof_path.read_bytes()

    def test_verify_rust_proof(self, program_name, vectors, proof_binary):
        """Verifier accepts a valid proof from the Rust prover."""
        assert False, (
            f"Not implemented: verify Rust proof for '{program_name}' "
            f"({len(proof_binary)} bytes)"
        )

    def test_reject_corrupted_proof(self, program_name, vectors, proof_binary):
        """Verifier rejects a proof with a corrupted commitment."""
        assert False, f"Not implemented: reject corrupted proof for '{program_name}'"
