"""End-to-end STARK verifier tests.

These tests load proofs generated by the Rust prover and verify them
with the Python verifier implementation. This is the north star test:
if the Python verifier accepts Rust-generated proofs, the spec is correct.

Vectors are in tests/test-data/e2e/.

- ``fibonacci_stark`` is always available (fast, single-AIR).
- ``rv32im_fibonacci`` is included when its vectors exist (heavy generation).
- ``revm_transfer`` is included when its vectors exist (heavy generation).
"""
import copy
import json
import random

import pytest
from helpers import load_test_vectors, e2e_program_params

from protocol.proof import (
    parse_proof_json,
    parse_vk_json,
    parse_fri_params,
)
from protocol.stark import (
    VerificationError,
    verify_stark,
)


def _load_e2e(vectors):
    """Parse proof, VK, and FRI params from e2e test vectors.

    Returns (proof, vk, fri_params).
    """
    assert "verifying_key" in vectors and "vk_bytes_hex" in vectors["verifying_key"], (
        "VK data not available — regenerate test vectors"
    )

    proof_bytes = bytes.fromhex(vectors["proof_bytes_hex"])
    proof_json = json.loads(proof_bytes)
    proof = parse_proof_json(proof_json)

    vk_bytes = bytes.fromhex(vectors["verifying_key"]["vk_bytes_hex"])
    vk_json = json.loads(vk_bytes)
    vk = parse_vk_json(vk_json)

    fri_params = parse_fri_params(vectors["fri_params"])
    return proof, vk, fri_params


def _flip_random_element(field_list: list) -> int:
    """XOR a random element in a list[int] with a random nonzero mask. Returns index."""
    idx = random.randrange(len(field_list))
    mask = random.randint(1, (1 << 31) - 1)
    field_list[idx] ^= mask
    return idx


class TestStarkVerifierE2E:
    """Python verifier accepts proofs generated by OpenVM Rust prover."""

    @pytest.fixture(params=e2e_program_params())
    def program_name(self, request):
        return request.param

    @pytest.fixture
    def vectors(self, program_name):
        return load_test_vectors("e2e", program_name)

    def test_verify_valid_proof(self, program_name, vectors):
        """Verifier accepts a valid proof from the Rust prover."""
        proof, vk, fri_params = _load_e2e(vectors)
        verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_quotient_commitment(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted quotient commitment."""
        proof, vk, fri_params = _load_e2e(vectors)
        _flip_random_element(proof.commitments.quotient)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_main_commitment(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted main trace commitment."""
        proof, vk, fri_params = _load_e2e(vectors)
        commit = random.choice(proof.commitments.main_trace)
        _flip_random_element(commit)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_after_challenge_commitment(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted after-challenge commitment."""
        proof, vk, fri_params = _load_e2e(vectors)
        if not proof.commitments.after_challenge:
            return  # Simple AIRs (e.g. fibonacci) have no after-challenge commitments
        commit = random.choice(proof.commitments.after_challenge)
        _flip_random_element(commit)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_public_value(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted public value."""
        proof, vk, fri_params = _load_e2e(vectors)

        # Collect all AIRs that have public values, pick one at random
        airs_with_pvs = [ap for ap in proof.per_air if ap.public_values]
        assert airs_with_pvs, "No AIR with public values — test vector is incomplete"
        ap = random.choice(airs_with_pvs)
        _flip_random_element(ap.public_values)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_wrong_vk(self, program_name, vectors):
        """Verifier rejects a proof verified against a modified VK."""
        proof, vk, fri_params = _load_e2e(vectors)
        _flip_random_element(vk.pre_hash)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_opened_main_values(self, program_name, vectors):
        """Verifier rejects a proof with corrupted opened main trace values."""
        proof, vk, fri_params = _load_e2e(vectors)

        # Pick a random main trace opening and corrupt one FF4 coefficient
        all_main = proof.opening.values.main
        assert all_main, "No main trace openings"
        batch = random.choice(all_main)
        adj = random.choice(batch)
        row = random.choice([adj.local, adj.next])
        assert row, "Opened values row should not be empty"
        elem = random.choice(row)
        _flip_random_element(elem)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_quotient_opened_values(self, program_name, vectors):
        """Verifier rejects a proof with corrupted opened quotient values."""
        proof, vk, fri_params = _load_e2e(vectors)

        # proof.opening.values.quotient is list[list[list[FF4Coeffs]]]
        all_quot = proof.opening.values.quotient
        assert all_quot, "No quotient openings"
        air_quots = random.choice(all_quot)
        chunk = random.choice(air_quots)
        elem = random.choice(chunk)
        _flip_random_element(elem)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_fri_commit(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted FRI commit-phase commitment."""
        proof, vk, fri_params = _load_e2e(vectors)

        commits = proof.opening.proof.commit_phase_commits
        assert commits, "No FRI commit-phase commitments"
        commit = random.choice(commits)
        _flip_random_element(commit)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_fri_final_poly(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted FRI final polynomial."""
        proof, vk, fri_params = _load_e2e(vectors)

        final_poly = proof.opening.proof.final_poly
        assert final_poly, "No FRI final polynomial"
        coeff = random.choice(final_poly)
        _flip_random_element(coeff)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_fri_query_sibling(self, program_name, vectors):
        """Verifier rejects a proof with a corrupted FRI query sibling value."""
        proof, vk, fri_params = _load_e2e(vectors)

        qproofs = proof.opening.proof.query_proofs
        assert qproofs, "No FRI query proofs"
        qp = random.choice(qproofs)
        step = random.choice(qp.commit_phase_openings)
        _flip_random_element(step.sibling_value)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)

    def test_reject_corrupted_input_proof_values(self, program_name, vectors):
        """Verifier rejects a proof with corrupted PCS input proof values."""
        proof, vk, fri_params = _load_e2e(vectors)

        qproofs = proof.opening.proof.query_proofs
        assert qproofs, "No FRI query proofs"
        qp = random.choice(qproofs)
        assert qp.input_proof, "No input proof batches"
        batch = random.choice(qp.input_proof)
        assert batch.opened_values, "No opened values in batch"
        row = random.choice(batch.opened_values)
        assert row, "Empty opened values row"
        idx = random.randrange(len(row))
        row[idx] ^= random.randint(1, (1 << 31) - 1)

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)
