"""End-to-end STARK prover tests.

These tests exercise the complete proving pipeline: trace generation,
constraint evaluation, polynomial commitment, FRI, and proof serialization.

Vectors are in tests/test-data/e2e/.

- ``fibonacci_stark`` uses the Python prover for byte-for-byte comparison.
- ``rv32im_fibonacci`` and ``revm_transfer`` are verified with the Python verifier
  (trace generation requires the full VM pipeline).
"""
import copy
import json
import random

import pytest
from helpers import load_test_vectors, e2e_program_params

from protocol.proof import (
    parse_proof_json,
    parse_vk_json,
    parse_fri_params,
    serialize_proof_json,
)
from protocol.stark import (
    VerificationError,
    prove_stark,
    verify_stark,
)
from witness.fibonacci import generate_fibonacci_trace


def _load_e2e(vectors):
    """Parse VK and FRI params from e2e test vectors."""
    if "verifying_key" not in vectors or "vk_bytes_hex" not in vectors["verifying_key"]:
        pytest.skip("VK data not available — regenerate test vectors")

    vk_bytes = bytes.fromhex(vectors["verifying_key"]["vk_bytes_hex"])
    vk_json = json.loads(vk_bytes)
    vk = parse_vk_json(vk_json)
    fri_params = parse_fri_params(vectors["fri_params"])
    return vk, fri_params


class TestStarkProverE2E:
    """Full STARK prover produces proofs matching the Rust implementation."""

    def test_proof_binary_equivalence(self):
        """Python prover output matches Rust prover output byte-for-byte."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        # Generate trace from known initial values
        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        # Run Python prover
        proof = prove_stark(vk, [trace], [pvs], fri_params)

        # Serialize and compare byte-for-byte
        proof_dict = serialize_proof_json(proof)
        proof_json_bytes = json.dumps(proof_dict, separators=(",", ":")).encode()
        proof_hex = proof_json_bytes.hex()

        expected_hex = vectors["proof_bytes_hex"]
        assert proof_hex == expected_hex, (
            f"Proof mismatch: Python={len(proof_json_bytes)} bytes, "
            f"Expected={len(expected_hex) // 2} bytes"
        )

    def test_trace_commitment(self):
        """Trace commitment matches golden value."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        proof = prove_stark(vk, [trace], [pvs], fri_params)

        expected = vectors["main_trace_commitments"]
        assert proof.commitments.main_trace == expected

    def test_quotient_commitment(self):
        """Quotient polynomial commitment matches golden value."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        proof = prove_stark(vk, [trace], [pvs], fri_params)

        expected = vectors["quotient_commitment"]
        assert proof.commitments.quotient == expected

    def test_prover_output_passes_verifier(self):
        """Proof generated by the Python prover passes the Python verifier."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        proof = prove_stark(vk, [trace], [pvs], fri_params)
        verify_stark(vk, proof, fri_params)

    def test_corrupted_proof_rejected(self):
        """Corrupting a single byte of the proof causes verification failure."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        proof = prove_stark(vk, [trace], [pvs], fri_params)

        # Corrupt the quotient commitment
        proof.commitments.quotient[0] ^= 1

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)
