"""End-to-end STARK prover tests.

These tests exercise the complete proving pipeline: trace generation,
constraint evaluation, polynomial commitment, FRI, and proof serialization.

Vectors are in tests/test-data/e2e/.

- ``fibonacci_stark`` uses the Python prover for byte-for-byte comparison.
- ``rv32im_fibonacci`` uses the Python prover for byte-for-byte comparison (multi-AIR).
- ``revm_transfer`` is verified with the Python verifier
  (trace generation requires the full VM pipeline).
"""
import copy
import json
import random
from pathlib import Path

import pytest
from helpers import load_test_vectors, e2e_program_params

from protocol.proof import (
    parse_proof_json,
    parse_prover_inputs,
    parse_vk_json,
    parse_fri_params,
    serialize_proof_json,
)
from protocol.stark import (
    VerificationError,
    prove_stark,
    verify_stark,
)
from witness.fibonacci import generate_fibonacci_trace


def _load_e2e(vectors):
    """Parse VK and FRI params from e2e test vectors."""
    if "verifying_key" not in vectors or "vk_bytes_hex" not in vectors["verifying_key"]:
        pytest.skip("VK data not available — regenerate test vectors")

    vk_bytes = bytes.fromhex(vectors["verifying_key"]["vk_bytes_hex"])
    vk_json = json.loads(vk_bytes)
    vk = parse_vk_json(vk_json)
    fri_params = parse_fri_params(vectors["fri_params"])
    return vk, fri_params


class TestStarkProverE2E:
    """Full STARK prover produces proofs matching the Rust implementation."""

    def test_proof_binary_equivalence(self):
        """Python prover output matches Rust prover output byte-for-byte."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        # Generate trace from known initial values
        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        # Run Python prover
        proof = prove_stark(vk, [trace], [pvs], fri_params)

        # Serialize and compare byte-for-byte
        proof_dict = serialize_proof_json(proof)
        proof_json_bytes = json.dumps(proof_dict, separators=(",", ":")).encode()
        proof_hex = proof_json_bytes.hex()

        expected_hex = vectors["proof_bytes_hex"]
        assert proof_hex == expected_hex, (
            f"Proof mismatch: Python={len(proof_json_bytes)} bytes, "
            f"Expected={len(expected_hex) // 2} bytes"
        )

    def test_trace_commitment(self):
        """Trace commitment matches golden value."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        proof = prove_stark(vk, [trace], [pvs], fri_params)

        expected = vectors["main_trace_commitments"]
        assert proof.commitments.main_trace == expected

    def test_quotient_commitment(self):
        """Quotient polynomial commitment matches golden value."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        proof = prove_stark(vk, [trace], [pvs], fri_params)

        expected = vectors["quotient_commitment"]
        assert proof.commitments.quotient == expected

    def test_prover_output_passes_verifier(self):
        """Proof generated by the Python prover passes the Python verifier."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        proof = prove_stark(vk, [trace], [pvs], fri_params)
        verify_stark(vk, proof, fri_params)

    def test_corrupted_proof_rejected(self):
        """Corrupting a single byte of the proof causes verification failure."""
        vectors = load_test_vectors("e2e", "fibonacci_stark")
        vk, fri_params = _load_e2e(vectors)

        per_air = vectors["per_air"][0]
        pvs = per_air["public_values"]
        trace = generate_fibonacci_trace(pvs[0], pvs[1], per_air["degree"])

        proof = prove_stark(vk, [trace], [pvs], fri_params)

        # Corrupt the quotient commitment
        proof.commitments.quotient[0] ^= 1

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, proof, fri_params)


class TestMultiAirProverE2E:
    """Multi-AIR STARK prover: byte-for-byte equivalence with Rust.

    All tests share a single proof computation (cached at class level)
    since prove_stark is deterministic and takes ~5 minutes for rv32im.
    """

    # Class-level cache: computed once, shared across all test methods
    _cached_data = None

    @classmethod
    def _get_cached(cls):
        """Return (proof, vk, fri_params, vectors), computing once."""
        if cls._cached_data is not None:
            return cls._cached_data

        vectors = load_test_vectors("e2e", "rv32im_fibonacci")
        vk, fri_params = _load_e2e(vectors)

        # Load raw traces from separate file
        traces_path = (
            Path(__file__).resolve().parent
            / "test-data" / "e2e" / "rv32im_fibonacci_traces.json"
        )
        with open(traces_path) as f:
            traces_data = json.load(f)
        prover_inputs = parse_prover_inputs(traces_data)

        # Parse reference proof for public values
        proof_bytes = bytes.fromhex(vectors["proof_bytes_hex"])
        proof_json = json.loads(proof_bytes)
        ref_proof = parse_proof_json(proof_json)

        # Build prover arguments (indexed by proof AIR position, not VK AIR index)
        proof_air_ids = [ai.air_id for ai in prover_inputs.per_air]
        traces = [ai.common_main or [] for ai in prover_inputs.per_air]
        preprocessed = [ai.preprocessed for ai in prover_inputs.per_air]
        cached_mains = [ai.cached_mains for ai in prover_inputs.per_air]
        pvs = [ap.public_values for ap in ref_proof.per_air]

        proof = prove_stark(
            vk, traces, pvs, fri_params,
            preprocessed_traces=preprocessed,
            cached_main_traces=cached_mains,
            air_ids=proof_air_ids,
        )
        cls._cached_data = (proof, vk, fri_params, vectors)
        return cls._cached_data

    def test_rv32im_proof_binary_equivalence(self):
        """Python multi-AIR prover matches Rust output byte-for-byte."""
        proof, _, _, vectors = self._get_cached()

        proof_dict = serialize_proof_json(proof)
        proof_json_bytes = json.dumps(proof_dict, separators=(",", ":")).encode()
        proof_hex = proof_json_bytes.hex()

        expected_hex = vectors["proof_bytes_hex"]
        assert proof_hex == expected_hex, (
            f"Proof mismatch: Python={len(proof_json_bytes)} bytes, "
            f"Expected={len(expected_hex) // 2} bytes"
        )

    def test_rv32im_main_trace_commitment(self):
        """Main trace commitments match golden values."""
        proof, _, _, vectors = self._get_cached()
        expected = vectors["main_trace_commitments"]
        assert proof.commitments.main_trace == expected

    def test_rv32im_quotient_commitment(self):
        """Quotient polynomial commitment matches golden value."""
        proof, _, _, vectors = self._get_cached()
        expected = vectors["quotient_commitment"]
        assert proof.commitments.quotient == expected

    def test_rv32im_prover_output_passes_verifier(self):
        """Proof generated by the Python prover passes the Python verifier."""
        proof, vk, fri_params, _ = self._get_cached()
        verify_stark(vk, proof, fri_params)

    def test_rv32im_corrupted_proof_rejected(self):
        """Corrupting a single byte of the proof causes verification failure."""
        proof, vk, fri_params, _ = self._get_cached()

        # Deep copy so corruption doesn't affect other tests
        corrupted = copy.deepcopy(proof)
        corrupted.commitments.quotient[0] ^= 1

        with pytest.raises((VerificationError, AssertionError)):
            verify_stark(vk, corrupted, fri_params)
